# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_total_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_voted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
